### ISSUE TITLE
Some bugs finded

### ISSUE THREAD

**Issue by hmartiins** [PeruibeTEC/Mobile#20]
**Describe the bug**

I was testing the app and I ended up finding some bugs like error loading fonts, unusual button style and component placement errors. Below are the images of the errors found. In Project Screen, the post timing is out of line with the rest of the content. In Restaurant Screen the header is being cut. In Detail Restaurant the "View Menu" button is taking up the entire screen. On Home Screen when you click on the hamburger menu icon the navigation error appears.

**To Reproduce**

1. Go to 'Project Screen'
2. Go to 'Restaurant Screen'
3. Go to 'Detail Restaurant Screen'
4. Go to 'Home Screen' and click on 'Burguer' Menu

**Screenshots**
Below are the images of the problems, respectively as described above.

1st
![image](https://user-images.githubusercontent.com/51277667/139550328-490732b6-eef4-441b-8a5f-bbe66f4773eb.png)
2nd
![image](https://user-images.githubusercontent.com/51277667/139550409-cd7b1507-5891-4803-a380-92ffa1d94cd7.png)
3rd
![image](https://user-images.githubusercontent.com/51277667/139550468-73be6507-ff23-42e7-be01-a047b76d1d79.png)
4th
![image](https://user-images.githubusercontent.com/51277667/139550518-12a93a18-3296-4a25-a3df-8fc7643b7d5b.png)
5th
![image](https://user-images.githubusercontent.com/51277667/139550570-f8d8ff06-65cc-47a3-80c8-e8896c6da53c.png)
6th
![image](https://user-images.githubusercontent.com/51277667/139550628-f29431fd-5477-4068-adf2-3c773471c604.png)

**Comment by joaovds** [comment]
@hmartiins These errors are in the "Main" branch, right?

**Comment by hmartiins** [comment]
hey @joaovds, I cloned the make-the-access-flow-functional branch and saw these errors there, after that I gave a git pull origin main and the error persisted.
